version: '3.4'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password@12345#
    ports:
      - 5434:5432
    networks:
      - my_network

networks:
  my_network:
